### ISSUE TITLE
add printf() support

### ISSUE THREAD

**Issue by SpenceKonde** [SpenceKonde/DxCore#13]
MegaCoreX has this. DxCore and megaTinyCore should, but don't.

**Comment by MCUdude** [comment]
Are you 100% sure that DxCore and megaTinyCore don't have printf?

https://github.com/SpenceKonde/DxCore/blob/e3789005948d00a8e1018b22046134c35c65128a/megaavr/cores/dxcore/api/Print.h#L81-L82

https://github.com/SpenceKonde/DxCore/blob/e3789005948d00a8e1018b22046134c35c65128a/megaavr/cores/dxcore/api/Print.cpp#L207-L227

**Comment by SpenceKonde** [comment]
Huh, someone complained about them not being in, didnt have time to check...

____________
Spence Konde
Azzy’S Electronics

New products! Check them out at tindie.com/stores/DrAzzy
GitHub: github.com/SpenceKonde
ATTinyCore: Arduino support for almost every ATTiny microcontroller
Contact: spencekonde@gmail.com

**Comment by MCUdude** [comment]
You can safely close this. I used DxCore `Serial1.printf` yesterday, and it works perfectly.

Personally, I _love_ printf, and it's stupid, strange, and sad that the Arduino developers refuse to add it to the print class. It's very useful for other things than Serial too. Since it's available for use with all libraries, it works out of the box on a bunch of LCD/OLED/TFT libraries. I've been using printf with the U8g2 graphical library
(`u8g2.printf(F("Hello World %d\n"), myVal);`), and it's just excellent.

**Comment by sstaub** [comment]
Can also confirm that printf works. The report from me in #5 was wrong, Sorry.
