### ISSUE TITLE
printf() does not show float numbers

### ISSUE THREAD

**Issue by mrWheel** [SpenceKonde/DxCore#151]
Given this code:
```
float fVal1 = 1.2345;
float fVal2 = 543.201;
int iVal = 123;

Serial.printf("This is a float [%f], this also [%5.3f] and this is an integer [%d]\n", fVal1, fVal2, iVal);
```
The output is:
```
This is a float [?], this also [    ?] and this is an integer [123]
```

`snprintf()` does not format floats either (just shows the question mark)!

**Comment by SpenceKonde** [comment]
Doesn;t that happen on all AVR Arduinos? I'm sure our printf is using one of the C functions internally (my guess without looking is that they use snprintf() to output to the TX ring buffer). , so it's not surprising that it would behave the same way. I think this behavior was intended for flash usage concerns, and I think there's a way to get it back for snprintf? I''ve never bothered to get used to printf myself.so I don;t gave any relevant experience. If the issue is just flash usage that led to it's removal (which I think is the case) it's easier to justify that sort of extravagance here,

**Comment by mrWheel** [comment]
As far as I know most AVR boards / cores don’t have `printf()` or `snprintf()`.
Your newer cores seem to have it but I have never used it with floats.
I can live without it but maybe something to mention in the documentation?

**Comment by SpenceKonde** [comment]
Aaahaa, I knew this sounded familiar....
Easy-peasy fix, it looks like? No record of anyone playing with it on the modernAVRs but I'd be shocked if it didn't work the same way.

**Comment by mrWheel** [comment]
@SpenceKonde 
Wauw! You have done a lot of work the last few day’s! Need a lot of time to read it all though.
Great work.
Thanks!

**Comment by nabelekt** [comment]
For what it's worth, this page has some informative discussion about the issue: https://www.e-tinkers.com/2020/01/do-you-know-arduino-sprintf-and-floating-point/
