### ISSUE TITLE
Internal clock with auto calibration from crystal oscillator

### ISSUE THREAD

**Issue by wa2mze** [SpenceKonde/DxCore#194]
Is there an option to use the internal 32khz crystal oscillator (with external crystal) to auto-calibrate the internal oscillator for the DA/DB cores?  I've seen code to do this in AtmelStart.

**Comment by SpenceKonde** [comment]
There is no internal 32 kHz crystal oscillator. Basically nothing has an internal crystal oscillator - its a very hard thing to fabricate from a materials perspective. There is a approximately 32kHz ultra low power (ULP) RC oscillator (ULP also reads accurately as Ultra Low Precision - it's "calibrated" like the classic AVR watchdog timers were), You can't tune the main clock off that because the internal HF oscillator is calibrated to the higher standard of the two (it's not even close). You can tune the internal HO from an external crystal which has nothing to do with the internal ULP oscillator other than their both being under the umbrella of the CLKCTRL peripheral. 

Assuming you're talking about using the external 32kHz nominal crystal to autotune, yes, the DxCore library included with the core provides wrappers aroundit:
https://github.com/SpenceKonde/DxCore/tree/master/megaavr/libraries/DxCore

There's example code in the readme because it wasnt worth making a separate sketch to demo. It's pretty dead simple. 

It's sort of a disappointing feature IMO - there's just one tiny thing they did that took all it's potential away....
The granularity of the HF internal oscillator is too coarse. 0.4%. Most parts will change at most one notch that way. unless you're using at weirdly high temoperatures.... I wasn't even sure it was working until I aimed the heatgun at and watched ithe frequency of it's PWM on the scope  with and without autotune. 

You will see basically no effect from varying voltage. The oscillator doesn't see the voltage that the outside world sees, it would appear to run on the 1.x v internal core voltage. 

You get approx 16 steps in either direction, 0.4/step = +/- 6.4%adjusted too coarsely. 

You probably won't notice that the tuning worked (and the tuning registers is unreadable while it's enabled. 

The tinyAVRs are a totally different ballgame. A much more fun one, in this way - 0/1-series have 64 options, and they span a range from like 12 to 33 MHz ( give or take a few) from 20 nominal, 10-27 from 16-nominal. Some lucky extended temp range parts can hit 30 at room temp and be stable (32 with ext clock is possible for such chips, too)
The 2-series is even better - twice the granularity, slightly higher speeds, so that fused for 16, the chips sometimes kiss 30 MHz, and fused for 20, hitting 32 is easypeasy, and almost all are stable there. Pretty soon you'll be able to self-tune them to get athe cal byte for the desired speed **without a reference** by trusting the insanely accurate factory cal at 3-5V and room temp, That'll be in megaTinyCore 2.4.4 (and that already supports tuning with a reference and writing the values to the USERROW , so if you then select a tuned speed, it uses that stored value, that you know works. Tunes in a few seconds to get those values (also dumps a buch of interesting info about your part to the console) , but you need a 500Hz reference clock (for now), or a 1 kHz one like most scopes will generate.
