### ISSUE TITLE
SERIAL_RX_BUFFER_SIZE/SERIAL_TX_BUFFER_SIZE

### ISSUE THREAD

**Issue by ObviousInRetrospect** [SpenceKonde/DxCore#297]
Three questions some of which are probably low priority feature requests:

1. Is there any way to adjust SERIAL_RX_BUFFER_SIZE/SERIAL_TX_BUFFER_SIZE without hacking ~/Library/arduino15/.../UART.h? Doing this per-project would be great. Ideal interface would be either a #define in the project or a header in the project that can be included to override. Less awesome would be a menu item which I know how to hack into boards.txt but its a lot of settings.

2. Is there any way to set different SERIAL_RX_BUFFER_SIZE/SERIAL_TX_BUFFER_SIZE per-uart? on the parts with 3-5 uarts, 256b per buffer adds up when I only need one of them to be big (or is the same ISR shared by all ports in a way that makes that slower?). The use case here is background GPS acquisition and being able to buffer the full (reduced) spew generated by the GPS until some other time-critical task finishes without interleaving a bunch of serial checks.

3. Any chance there is a way to register a callback or an isr when the rx buffer is full | has k bytes left? (k should probably be a small constant or 1/4 the buffer or something depending on whether the notification is an isr or a slower callback) - best I can come up with is a PIT isr checking .available().

**Comment by SpenceKonde** [comment]
MX682X hit the nail on the head. 

The code supports 256b buffers absolute maximum, and they cannot be set per serial port, and you'd need to edit the variant for that. They absolutely cannot be set per-port basis without either a second copy of the RXC ISR with corresponding adjustmetns to the inline assembly across at least two files. 

But this is an X-Y problem as far as I am concerned unless you can explain to me why you need such a gigantic buffer and why the correct solution isn't to read the data out as it comes in and store it in a global (or static) buffer that is large enough to hold however much data you need in order to do what you need to do. 

If you need a >256b receive buffer within the hardware serial classs, you are doing something fundamentally wrong. You should have a global or static buffer large enough to fit the largest amount of data you might need to have at any given time, and your code should not be getting lost in some slow-running routine for >64*10 = 640 bit periods (115200 baud, that's 5.5 milliseconds without your code doing something like `while Serial.available() buff[idx++] = Serial.read()` Why are you not able to meet the constraint of emptying the rx buffer into another buffer at least once per 640 bit periods? T
