### ISSUE TITLE
Verification error uploading large program to AVR128DB via Optiboot

### ISSUE THREAD

**Issue by technoblogy** [SpenceKonde/DxCore#370]
I've been using Optiboot to upload a program to an AVR128DB48 with the **AVR DB-series (Optiboot)** Board option (DxCore 1.4.10), and I seem to get an avrdude verification error if the program grows beyond about 64K.

I tried adjusting the program size by gradually increasing the size of a PROGMEM string and found the critical point was as follows:

    Sketch uses 64512 bytes (49%) of program storage space. Maximum is 130560 bytes.

uploads fine, but adding one character to the PROGMEM string seems to increase the size of the program by 2 bytes (!) and gives:

    Sketch uses 64514 bytes (49%) of program storage space. Maximum is 130560 bytes.
     ...
    avrdude: verification error, first mismatch at byte 0x0200
             0xff != 0x0c
    avrdude: verification error; content mismatch
    avrdude: verification error; content mismatch

**Comment by SpenceKonde** [comment]
I think you'll find that the program, in fact, has been uploaded successfully.

**Comment by technoblogy** [comment]
Ah, thanks. I can live with that!

**Comment by SpenceKonde** [comment]
Does the problem reproduce if you add, instead of 1 byte, 513 bytes?

Because something isn't adding up here... 

64514 bytes, added to a 512b bootloader is 65526, that is, 2 bytes of the way into the last page on the lower half of the memory... So why would RAMPZ be getting set? But that's almost certainly what's happening

**Comment by technoblogy** [comment]
You're right! Adding a further 512 bytes gets rid of the verification error:

| Sketch uses | Content mismatch? |
| ----------- | ----------------- |
| 64512       | No |
| 64514       | Yes |
| ... | Yes |
| 65024       | Yes |
| 65026       | No |

**Comment by SpenceKonde** [comment]
Well, this is thoroughly strange. Why would a write to the last page on the low half trigger this behavior, but a write that touched bytes after 0xFFFF *not* cause the bug? It is as if avrdude is triggering rampz being set by writing just 1 word, when it should take 256 words exactly to trigger that. Actually no even that I don't know how to fix, short of using SPM instead of SPM Z+ and manually incrementing the Z pointer, and *hoping* that avrdude is smart enough to tell it to load rampz, because it it's not, then I would have to put logic into the bootloader. We don't have space for that. We have I think 5 instruction words of space left on 128k parts..... 

BUT IT SHOULD ONLY BE MANIFESTING WHEN YOU WRITE EXACTLY 65024 BYTES!!!
Yet it's manifesting when you write anything in that final page, not the full page.

**Comment by technoblogy** [comment]
I confirm that the program seems to have uploaded OK even when you get the verification error, so I suggest treating it as a cosmetic annoyance, and perhaps add a note in the documentation. If it's not trivial to fix, it doesn't seem worth spending time on.

**Comment by SpenceKonde** [comment]
What configuration are you using? (serial port, alt vs non-alt, and whether it's the 1-sec external reset, or the 8-second all-source one) 

I have an idea to fix it, but I don't know if it will work without breaking uploads larger than 64k, I've got a laundry list of other testing to do, and I need to sort out a crashed NAS system on my home network (rescuing data from the surviving drive (it's mirrored 2-disk RAID) and replacing the harddrives with new ones) so it would be super helpful if you were able to check it since you have a sketch on hand to test it with and are the one who's got it reproducing on demand.

**Comment by technoblogy** [comment]
It's everything left at default:

<img width="737" alt="Screen Shot 2022-11-20 at 08 57 44" src="https://user-images.githubusercontent.com/22325291/202893780-0f1270dc-4dea-4064-a302-3ecc1e55774f.png">

**Comment by technoblogy** [comment]
In case it's helpful in tracking down the problem I've added in the length of the const char PROGMEM string that I've been adjusting to debug the error:

| Length of string | Sketch uses | Content mismatch? |
| ---------------- | ------------ | ------------------- |
| 393 | 64512       | No |
| 394 | 64514       | Yes |
| 395 | 64514       | Yes |
| ... | ... | Yes |
| 904 | 65024      | Yes |
| 905 | 65024       | Yes |
| 906 | 65026      | No |
| 907 | 65026       | No |

The "Sketch uses" figure reported by the Arduino IDE doesn't increase consistently as I increase the length of the PROGMEM string, but there's a discontinuity around the region where the mismatch error occurs. Perhaps a clue?

**Comment by SpenceKonde** [comment]
[optiboot_dx128_ser0.txt](https://github.com/SpenceKonde/DxCore/files/10049599/optiboot_dx128_ser0.txt)
Rename the file to a .hex (github doesn't let you attach .hex files! They'll let me attach a million other file types, many of which use file viewers with exploitable vulnerabilities.... so I could send a malicious video file that would pwn you if you were using the right (wrong) video player, but I can't attach a hex file... to an issue... on a repo with 276 hex files in it.... What sense does that make? 👎 )

**Comment by technoblogy** [comment]
Just to check I did it right, I put it in:

    /Users/david/Library/Arduino15/packages/DxCore/hardware/megaavr/1.4.10/bootloaders/hex

then did **Burn Bootloader** via SerialUPDI, then uploaded my test program via an FTDI board.

Unfortunately it still gives a mismatch error, although this time it's a bit different:

    avrdude: verification error, first mismatch at byte 0x033a
             0xff != 0x74
    avrdude: verification error; content mismatch
    avrdude: verification error; content mismatch

**Comment by SpenceKonde** [comment]
oh my. 

that is much more mysterious.... o_O

And is the bootloader bootlooping for you too? I seem to have done something wrong with the entry conditions...

**Comment by technoblogy** [comment]
What's bootlooping?

Is it flashing the LED_BUILTIN with two short flashes repeated. It stops flashing after the upload with verification error.

**Comment by SpenceKonde** [comment]
Well, the upload in this case is straight up failing, yasee. 

OH! BUT YOUR CODE DOESN'T CARE BECAUSE THE FAILURE IS IN THE MIDDLE OF PROGMEM!  0x33A would still be in the giant block of progmem.... In my case, it's dirty resetting because it's a big chunk of app code that's missing.

**Comment by SpenceKonde** [comment]
One big difference though. For me, it verifies despite NOT BEING UPLOADED SUCCESSFULLY.

**Comment by SpenceKonde** [comment]
AAAAHAAAA!!!!! It NEVER should have worked! 
It was just getting lucky! 
The inline assembly calls a function. That function has registers assigned by the compiler that it uses - r24 (used to pass the function arguments) and some other register. r24 I was expecting. What I wasn't thinking about was the second register. In the past it happened to be something that didn't matter. This time the compiler happened to pick r25. Which is the same register it gave length to me in.

**Comment by technoblogy** [comment]
Not sure I completely follow all that, but it sounds like you're onto something!

**Comment by SpenceKonde** [comment]
Here's a version with that issue fixed. 
[optiboot_dx128_ser0.txt](https://github.com/SpenceKonde/DxCore/files/10050284/optiboot_dx128_ser0.txt)

**Comment by technoblogy** [comment]
I've tested the cases that gave Content Mismatch before:

| Length of string | Sketch uses | Content mismatch? |
| ---------------- | ------------ | ------------------- |
| 394 | 64514       | No |
| 395 | 64514       | No |
| 904 | 65024      | No |
| 905 | 65024      | No |

Looks good. Well done!

**Comment by SpenceKonde** [comment]
Sweet. 

Does it work with a sketch that uses 65026 bytes is the real question? That's what I was most worried about tbh - that would bring the sketch size over the threshold to where it does need RAMPZ to be set. And I'm not certain that this will happen correctly; whereas before, the use of SPM Z+ ensured that it didn't need to be told that... now it relies on a load extended address command being sent by AVRdude.

**Comment by technoblogy** [comment]
The program I was originally developing has by now grown to 66408 bytes and that seems to be working fine. Or do I need to test exactly 65026 bytes?

**Comment by SpenceKonde** [comment]
Nope, we're good now. Sweet. That was an easier fix than I expected

**Comment by technoblogy** [comment]
Sorry, but there does seem to be something not quite right about your latest bootloader. After uploading my program via serial, when I reapply power LED_BUILTIN flashes twice, and there's a delay before my program runs. This didn't happen with the original bootloader (that gave content mismatch errors).
