### ISSUE TITLE
How to connect the AVR128DB128 to external crystal 

### ISSUE THREAD

**Issue by unebonnevie** [SpenceKonde/DxCore#408]
Hi,

I looked over https://github.com/SpenceKonde/DxCore/blob/master/megaavr/extras/DA28.md but am not seeing any mentioning of connecting the AVR128DB28 with external crystal.  I understand that the DxCore for Arduino is meant to work with the default 24Mhz internal clock.  But what if one wants to connect to an external crystal of some specific Mhz?   I am happy, per the below image, that DxCore even supports overclocked speeds.

It looks to me (from the datasheet) that for external crystals with HIGH frequencies the pins to connect to are PA0 and PA1.  For the 32.768khz crystal, I can simply connect to PF0 and PF1 pins.44

Thanks!

![Mhz](https://user-images.githubusercontent.com/14103779/221389046-b0ab162e-a863-4ecf-8e70-cba9c4594e12.png)

![crystals](https://user-images.githubusercontent.com/14103779/221389250-2f3d7bb4-2288-4432-875c-b5ae803410c7.png)

**Comment by SpenceKonde** [comment]
Yup, and then set the clock option appropriately, and if it starts up running WAY slower (as if it were running at 4 MHz, the external clock or crystal isn't operating. It can't soft brick the chip like classic AVRs. 

The devil of course is in the details - The crystal oscillator circuit on the modern AVRs is more efficient than the old one that the classic AVRs used, but TANSTAAFL applies here. The price in this case is that because it's not shoving the crystal as hard, the crystal is more likely to not oscillate properly at all. Loading capacitor values need to be closer (You certainly can't just match the cap's capacitance with a pair of caps and expect it to work like you could on classic AVRs - Those pins have capacitance, those traces have capacitance, and you have to account for that. The modern AVRs seem to like surprisingly small load caps, and I've had ones even with very short traces actually oscillate well enough to work without the caps at all (though they would usually stop oscillating if you touched the housing of the crystal). I've seen several formulas that are supposed to give load capacitor values, but there are several different (very different) equations going around, and no matter, usually none of them worked. I've had good luck with 4.7pF caps on 12pF crystals, and 6.8 or 8.2pF ones on 18pF crystals. Oh - and CFD is not very effective at detecting a malfunctioning crystal - it will often generate enough transitions to keep CFD happy, but violate the maximum pulse length maximum or otherwise generate an unsuitable clock, leading to math errors and dirty resets (and if you never get the crystal oscillating at all, eventually it gives up and falls back to 4 MHz. CFD helps more with an external clock which might stop under control of some other controller, and you want to react to that by falling back to internal clock. 

The 32k crystals are even worse in terms of sensitivity to capacitance and layout, since they're specifically  designed for very low power; the datasheet gives further guidance in oscillator section of the electrical properties chapter. It is not unusual for me to determine the values of the loading caps empirically (that is, I have to try several capacitor values (using the same cap on each pin of course) if I have a different board or crystal, if I want it to work.
