### ISSUE TITLE
printf not handling int32_t value properly

### ISSUE THREAD

**Issue by Warren52** [SpenceKonde/DxCore#449]
// ------- debug aid - left off
  //  Note: If someValue is int, printf() below works fine.
  //        If someValue is int16_t, works fine.
  //        If someValue is int32_t, the second someValue prints as 0
  //        If someValue is int32_t and int16_t casts are put before
  //          both someValue's, works fine.
  //        If someValue is int16_t and int32_t casts are put before
  //          both someValue's, the second someValue prints as 0
  //        Using Arduino IDE 1.8.19 with AVR128DB28 MCU
  //        Have DX Core version 1.5.8 installed
  // int someValue = 2399;
  int16_t someValue = 2399;
  // int32_t someValue = 2399;
  // Serial.printf("sm: %d  %d\n",(int32_t)(someValue), (int32_t)(someValue));
  //
  //  In the following, first prints ok, second is 0, third prints ok, forth is 0
  Serial.printf("sm: %d  %d %d %d \n",(int32_t)(someValue), (int32_t)(someValue), (int32_t)(someValue), (int32_t)(someValue));

**Comment by SpenceKonde** [comment]
You are using the wrong format specifiers. That's expected to corrupt the internal state of printf and not print the right amount of data. 
to print a 32-bit datatype, you need to use the appropriate length modifier. Those need to be %ld if you're printing a long. %d is only for printing int-size datatypes. See core README file, where I discuss this because it is such a common point of confusion (because, I think, people learned C on desktop computers, with 32-bit ints, so %d is correct for an int32_t. But %d is the correct format specifier *for an int* not *for a 32-bit integer* - it just happens that a PC has 32 bit integers (that's the size datatype their hardware is built to work with comfortably). And since a 32-bit integer is enough for almost all purposes... it's very easy to not know that length specifiers even exist.
See:

https://github.com/SpenceKonde/DxCore#warning-printf-and-variants-thereof-have-many-pitfalls

Or one of the first google hits

https://www.alphacodingskills.com/c/c-format-specifiers.php
