### ISSUE TITLE
 10bit  DAC with analogWrite give have only 8bit resolution (DD series  and other?)

### ISSUE THREAD

**Issue by nxplace** [SpenceKonde/DxCore#498]
I think we lose resolution with analogWrite. There is a 10bit DAC on the DD series and the code seem to use only 8bit.
```
  #if defined(DAC0_DATAH)
        DAC0.DATAH = val;
        DAC0.CTRLA |= 0x41; // OUTEN = 1, ENABLE = 1, but don't trash run stby
  #else
        DAC0.DATA = val;
        DAC0.CTRLA |= 0x41; // OUTEN = 1, ENABLE = 1, but don't trash run stby
  #endif
```

Should me something like:
```
/* Mask needed to get the 2 LSb for DAC Data Register */
#define LSB_MASK (0x03)
```
...
```
  #if defined(DAC0_DATAH)
        DAC0.DATAL = (val & LSB_MASK) << 6;
        /* Store the eight MSbs in DAC0.DATAH */
        DAC0.DATAH = val >> 2;
        DAC0.CTRLA |= 0x41; // OUTEN = 1, ENABLE = 1, but don't trash run stby
  #else
        DAC0.DATA = val;
        DAC0.CTRLA |= 0x41; // OUTEN = 1, ENABLE = 1, but don't trash run stby
  #endif
```

Thank you for you nice job!

**Comment by SpenceKonde** [comment]
Of course you lose resolution with digital write when writing to a 10 bit output when you only can only pass a number between 0 and 255!

This is a constraint imposed by compatibility with the Arduino API - "analogWrite(pin,val) will set the pin low if val =0,y  high if val = 255, and otherwise either PWM or use the DAC to output the voltage. 

It is an exercise for the user if they wish to write a new function which exposes the full resolution. That function would not be analogWrite, because analog write explicitly doesn't do what you want it to, and this is one of the few cases where the arduino documentation is unambiguous. While we *try* to expose functionality when possible, we do not do it if it would break the classic API. There are very very few places where I explicitly break with the API, and I did it only because what they were doing was so catastrophically wrong that something had to be done about it. 

So I can't see how this is a bug -buit the behavior you request absolutely would be considered a bug...
